name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:

  test:
    name: CI

    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          sudo apt update -y
          sudo apt-get install -y \
            fp-compiler-3.2.2 \
            openjdk-17-jdk \
            openjdk-17-source \
            dotnet-sdk-7.0

      - name: Compile
        run: sbt test:compile

      - name: Test
        run: sbt test
