name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:

  test:
    name: CI

    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            fp-compiler-3.2.2

      - name: Compile
        run: sbt test:compile

      - name: Test
        run: sbt test
